// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6G5cwciU5d9QDgKLlhle2WUYwNNu6irs',
    appId: '1:567683033096:web:607bffb3e1271bf35b49bd',
    messagingSenderId: '567683033096',
    projectId: 'get-it-done-ab165',
    authDomain: 'get-it-done-ab165.firebaseapp.com',
    storageBucket: 'get-it-done-ab165.appspot.com',
    measurementId: 'G-Q6NGLN8PK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiD8UBTssCQstpPvjZ1HuasatW2b0TILU',
    appId: '1:567683033096:android:1e37ce64db05d4935b49bd',
    messagingSenderId: '567683033096',
    projectId: 'get-it-done-ab165',
    storageBucket: 'get-it-done-ab165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUueFN9q12u9Lf8yOQ-SJQousej2MlOUE',
    appId: '1:567683033096:ios:e639c8699c8f1c485b49bd',
    messagingSenderId: '567683033096',
    projectId: 'get-it-done-ab165',
    storageBucket: 'get-it-done-ab165.appspot.com',
    iosBundleId: 'com.alumobiledev.getItDone',
  );
}
